Resources:
 MyInstance:
  Type: AWS::EC2::Instance
  Properties: 
    AvailabilityZone: "us-east-1"
    ImageId: ami-0574da719dca65348 
    InstanceType:  t2.micro
  

Type: AWS::EC2::SecurityGroupIngress
Properties: 
  CidrIp: 0.0.0.0/0
  Description: Enable SSH via port 22
  FromPort: 22
  IpProtocol: tcp
  ToPort: 22
